<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.10" tiledversion="1.11.2" name="Inside_C" tilewidth="32" tileheight="32" tilecount="576" columns="24">
 <image source="../Assets/Plataformas/Inside_C.png" width="768" height="768"/>
 <tile id="0" type="Plataforma"/>
 <tile id="1" type="Plataforma"/>
 <tile id="2" type="Plataforma"/>
 <tile id="3" type="Plataforma"/>
 <tile id="4" type="Plataforma"/>
 <tile id="5" type="Plataforma"/>
 <tile id="6" type="Plataforma"/>
 <tile id="7" type="Plataforma"/>
 <tile id="8" type="Plataforma"/>
 <tile id="9" type="Plataforma"/>
 <tile id="10" type="Plataforma"/>
 <tile id="11" type="Plataforma"/>
 <tile id="12" type="Plataforma"/>
 <tile id="13" type="Plataforma"/>
 <tile id="14" type="Plataforma"/>
 <tile id="15" type="Plataforma"/>
 <tile id="16" type="Plataforma"/>
 <tile id="17" type="Plataforma"/>
 <tile id="18" type="Plataforma"/>
 <tile id="19" type="Plataforma"/>
 <tile id="20" type="Plataforma"/>
 <tile id="21" type="Plataforma"/>
 <tile id="22" type="Plataforma"/>
 <tile id="23" type="Plataforma"/>
 <tile id="24" type="Plataforma"/>
 <tile id="25" type="Plataforma"/>
 <tile id="26" type="Plataforma"/>
 <tile id="27" type="Plataforma"/>
 <tile id="28" type="Plataforma"/>
 <tile id="29" type="Plataforma"/>
 <tile id="30" type="Plataforma"/>
 <tile id="31" type="Plataforma"/>
 <tile id="32" type="Plataforma"/>
 <tile id="33" type="Plataforma"/>
 <tile id="34" type="Plataforma"/>
 <tile id="35" type="Plataforma"/>
 <tile id="36" type="Plataforma"/>
 <tile id="37" type="Plataforma"/>
 <tile id="38" type="Plataforma"/>
 <tile id="39" type="Plataforma"/>
 <tile id="40" type="Plataforma"/>
 <tile id="41" type="Plataforma"/>
 <tile id="42" type="Plataforma"/>
 <tile id="43" type="Plataforma"/>
 <tile id="44" type="Plataforma"/>
 <tile id="45" type="Plataforma"/>
 <tile id="46" type="Plataforma"/>
 <tile id="47" type="Plataforma"/>
 <tile id="48" type="Plataforma"/>
 <tile id="49" type="Plataforma"/>
 <tile id="50" type="Plataforma"/>
 <tile id="51" type="Plataforma"/>
 <tile id="52" type="Plataforma"/>
 <tile id="53" type="Plataforma"/>
 <tile id="54" type="Plataforma"/>
 <tile id="55" type="Plataforma"/>
 <tile id="56" type="Plataforma"/>
 <tile id="57" type="Plataforma"/>
 <tile id="58" type="Plataforma"/>
 <tile id="59" type="Plataforma"/>
 <tile id="60" type="Plataforma"/>
 <tile id="61" type="Plataforma"/>
 <tile id="62" type="Plataforma"/>
 <tile id="63" type="Plataforma"/>
 <tile id="64" type="Plataforma"/>
 <tile id="65" type="Plataforma"/>
 <tile id="66" type="Plataforma"/>
 <tile id="67" type="Plataforma"/>
 <tile id="68" type="Plataforma"/>
 <tile id="69" type="Plataforma"/>
 <tile id="70" type="Plataforma"/>
 <tile id="71" type="Plataforma"/>
 <tile id="72" type="Plataforma"/>
 <tile id="73" type="Plataforma"/>
 <tile id="74" type="Plataforma"/>
 <tile id="75" type="Plataforma"/>
 <tile id="76" type="Plataforma"/>
 <tile id="77" type="Plataforma"/>
 <tile id="78" type="Plataforma"/>
 <tile id="79" type="Plataforma"/>
 <tile id="80" type="Plataforma"/>
 <tile id="81" type="Plataforma"/>
 <tile id="82" type="Plataforma"/>
 <tile id="83" type="Plataforma"/>
 <tile id="84" type="Plataforma"/>
 <tile id="85" type="Plataforma"/>
 <tile id="86" type="Plataforma"/>
 <tile id="87" type="Plataforma"/>
 <tile id="88" type="Plataforma"/>
 <tile id="89" type="Plataforma"/>
 <tile id="90" type="Plataforma"/>
 <tile id="91" type="Plataforma"/>
 <tile id="92" type="Plataforma"/>
 <tile id="93" type="Plataforma"/>
 <tile id="94" type="Plataforma"/>
 <tile id="95" type="Plataforma"/>
 <tile id="96" type="Plataforma"/>
 <tile id="97" type="Plataforma"/>
 <tile id="98" type="Plataforma"/>
 <tile id="99" type="Plataforma"/>
 <tile id="100" type="Plataforma"/>
 <tile id="101" type="Plataforma"/>
 <tile id="102" type="Plataforma"/>
 <tile id="103" type="Plataforma"/>
 <tile id="104" type="Plataforma"/>
 <tile id="105" type="Plataforma"/>
 <tile id="106" type="Plataforma"/>
 <tile id="107" type="Plataforma"/>
 <tile id="108" type="Plataforma"/>
 <tile id="109" type="Plataforma"/>
 <tile id="110" type="Plataforma"/>
 <tile id="111" type="Plataforma"/>
 <tile id="112" type="Plataforma"/>
 <tile id="113" type="Plataforma"/>
 <tile id="114" type="Plataforma"/>
 <tile id="115" type="Plataforma"/>
 <tile id="116" type="Plataforma"/>
 <tile id="117" type="Plataforma"/>
 <tile id="118" type="Plataforma"/>
 <tile id="119" type="Plataforma"/>
 <tile id="120" type="Plataforma"/>
 <tile id="121" type="Plataforma"/>
 <tile id="122" type="Plataforma"/>
 <tile id="123" type="Plataforma"/>
 <tile id="124" type="Plataforma"/>
 <tile id="125" type="Plataforma"/>
 <tile id="126" type="Plataforma"/>
 <tile id="127" type="Plataforma"/>
 <tile id="128" type="Plataforma"/>
 <tile id="129" type="Plataforma"/>
 <tile id="130" type="Plataforma"/>
 <tile id="131" type="Plataforma"/>
 <tile id="132" type="Plataforma"/>
 <tile id="133" type="Plataforma"/>
 <tile id="134" type="Plataforma"/>
 <tile id="135" type="Plataforma"/>
 <tile id="136" type="Plataforma"/>
 <tile id="137" type="Plataforma"/>
 <tile id="138" type="Plataforma"/>
 <tile id="139" type="Plataforma"/>
 <tile id="140" type="Plataforma"/>
 <tile id="141" type="Plataforma"/>
 <tile id="142" type="Plataforma"/>
 <tile id="143" type="Plataforma"/>
 <tile id="144" type="Plataforma"/>
 <tile id="145" type="Plataforma"/>
 <tile id="146" type="Plataforma"/>
 <tile id="147" type="Plataforma"/>
 <tile id="148" type="Plataforma"/>
 <tile id="149" type="Plataforma"/>
 <tile id="150" type="Plataforma"/>
 <tile id="151" type="Plataforma"/>
 <tile id="152" type="Plataforma"/>
 <tile id="153" type="Plataforma"/>
 <tile id="154" type="Plataforma"/>
 <tile id="155" type="Plataforma"/>
 <tile id="156" type="Plataforma"/>
 <tile id="157" type="Plataforma"/>
 <tile id="158" type="Plataforma"/>
 <tile id="159" type="Plataforma"/>
 <tile id="160" type="Plataforma"/>
 <tile id="161" type="Plataforma"/>
 <tile id="162" type="Plataforma"/>
 <tile id="163" type="Plataforma"/>
 <tile id="164" type="Plataforma"/>
 <tile id="165" type="Plataforma"/>
 <tile id="166" type="Plataforma"/>
 <tile id="167" type="Plataforma"/>
 <tile id="168" type="Plataforma"/>
 <tile id="169" type="Plataforma"/>
 <tile id="170" type="Plataforma"/>
 <tile id="171" type="Plataforma"/>
 <tile id="172" type="Plataforma"/>
 <tile id="173" type="Plataforma"/>
 <tile id="174" type="Plataforma"/>
 <tile id="175" type="Plataforma"/>
 <tile id="176" type="Plataforma"/>
 <tile id="177" type="Plataforma"/>
 <tile id="178" type="Plataforma"/>
 <tile id="179" type="Plataforma"/>
 <tile id="180" type="Plataforma"/>
 <tile id="181" type="Plataforma"/>
 <tile id="182" type="Plataforma"/>
 <tile id="183" type="Plataforma"/>
 <tile id="184" type="Plataforma"/>
 <tile id="185" type="Plataforma"/>
 <tile id="186" type="Plataforma"/>
 <tile id="187" type="Plataforma"/>
 <tile id="188" type="Plataforma"/>
 <tile id="189" type="Plataforma"/>
 <tile id="190" type="Plataforma"/>
 <tile id="191" type="Plataforma"/>
 <tile id="192" type="Plataforma"/>
 <tile id="193" type="Plataforma"/>
 <tile id="194" type="Plataforma"/>
 <tile id="195" type="Plataforma"/>
 <tile id="196" type="Plataforma"/>
 <tile id="197" type="Plataforma"/>
 <tile id="198" type="Plataforma"/>
 <tile id="199" type="Plataforma"/>
 <tile id="200" type="Plataforma"/>
 <tile id="201" type="Plataforma"/>
 <tile id="202" type="Plataforma"/>
 <tile id="203" type="Plataforma"/>
 <tile id="204" type="Plataforma"/>
 <tile id="205" type="Plataforma"/>
 <tile id="206" type="Plataforma"/>
 <tile id="207" type="Plataforma"/>
 <tile id="208" type="Plataforma"/>
 <tile id="209" type="Plataforma"/>
 <tile id="210" type="Plataforma"/>
 <tile id="211" type="Plataforma"/>
 <tile id="212" type="Plataforma"/>
 <tile id="213" type="Plataforma"/>
 <tile id="214" type="Plataforma"/>
 <tile id="215" type="Plataforma"/>
 <tile id="216" type="Plataforma"/>
 <tile id="217" type="Plataforma"/>
 <tile id="218" type="Plataforma"/>
 <tile id="219" type="Plataforma"/>
 <tile id="220" type="Plataforma"/>
 <tile id="221" type="Plataforma"/>
 <tile id="222" type="Plataforma"/>
 <tile id="223" type="Plataforma"/>
 <tile id="224" type="Plataforma"/>
 <tile id="225" type="Plataforma"/>
 <tile id="226" type="Plataforma"/>
 <tile id="227" type="Plataforma"/>
 <tile id="228" type="Plataforma"/>
 <tile id="229" type="Plataforma"/>
 <tile id="230" type="Plataforma"/>
 <tile id="231" type="Plataforma"/>
 <tile id="232" type="Plataforma"/>
 <tile id="233" type="Plataforma"/>
 <tile id="234" type="Plataforma"/>
 <tile id="235" type="Plataforma"/>
 <tile id="236" type="Plataforma"/>
 <tile id="237" type="Plataforma"/>
 <tile id="238" type="Plataforma"/>
 <tile id="239" type="Plataforma"/>
 <tile id="240" type="Plataforma"/>
 <tile id="241" type="Plataforma"/>
 <tile id="242" type="Plataforma"/>
 <tile id="243" type="Plataforma"/>
 <tile id="244" type="Plataforma"/>
 <tile id="245" type="Plataforma"/>
 <tile id="246" type="Plataforma"/>
 <tile id="247" type="Plataforma"/>
 <tile id="248" type="Plataforma"/>
 <tile id="249" type="Plataforma"/>
 <tile id="250" type="Plataforma"/>
 <tile id="251" type="Plataforma"/>
 <tile id="252" type="Plataforma"/>
 <tile id="253" type="Plataforma"/>
 <tile id="254" type="Plataforma"/>
 <tile id="255" type="Plataforma"/>
 <tile id="256" type="Plataforma"/>
 <tile id="257" type="Plataforma"/>
 <tile id="258" type="Plataforma"/>
 <tile id="259" type="Plataforma"/>
 <tile id="260" type="Plataforma"/>
 <tile id="261" type="Plataforma"/>
 <tile id="262" type="Plataforma"/>
 <tile id="263" type="Plataforma"/>
 <tile id="264" type="Plataforma"/>
 <tile id="265" type="Plataforma"/>
 <tile id="266" type="Plataforma"/>
 <tile id="267" type="Plataforma"/>
 <tile id="268" type="Plataforma"/>
 <tile id="269" type="Plataforma"/>
 <tile id="270" type="Plataforma"/>
 <tile id="271" type="Plataforma"/>
 <tile id="272" type="Plataforma"/>
 <tile id="273" type="Plataforma"/>
 <tile id="274" type="Plataforma"/>
 <tile id="275" type="Plataforma"/>
 <tile id="276" type="Plataforma"/>
 <tile id="277" type="Plataforma"/>
 <tile id="278" type="Plataforma"/>
 <tile id="279" type="Plataforma"/>
 <tile id="280" type="Plataforma"/>
 <tile id="281" type="Plataforma"/>
 <tile id="282" type="Plataforma"/>
 <tile id="283" type="Plataforma"/>
 <tile id="284" type="Plataforma"/>
 <tile id="285" type="Plataforma"/>
 <tile id="286" type="Plataforma"/>
 <tile id="287" type="Plataforma"/>
 <tile id="288" type="Plataforma"/>
 <tile id="289" type="Plataforma"/>
 <tile id="290" type="Plataforma"/>
 <tile id="291" type="Plataforma"/>
 <tile id="292" type="Plataforma"/>
 <tile id="293" type="Plataforma"/>
 <tile id="294" type="Plataforma"/>
 <tile id="295" type="Plataforma"/>
 <tile id="296" type="Plataforma"/>
 <tile id="297" type="Plataforma"/>
 <tile id="298" type="Plataforma"/>
 <tile id="299" type="Plataforma"/>
 <tile id="300" type="Plataforma"/>
 <tile id="301" type="Plataforma"/>
 <tile id="302" type="Plataforma"/>
 <tile id="303" type="Plataforma"/>
 <tile id="304" type="Plataforma"/>
 <tile id="305" type="Plataforma"/>
 <tile id="306" type="Plataforma"/>
 <tile id="307" type="Plataforma"/>
 <tile id="308" type="Plataforma"/>
 <tile id="309" type="Plataforma"/>
 <tile id="310" type="Plataforma"/>
 <tile id="311" type="Plataforma"/>
 <tile id="312" type="Plataforma"/>
 <tile id="313" type="Plataforma"/>
 <tile id="314" type="Plataforma"/>
 <tile id="315" type="Plataforma"/>
 <tile id="316" type="Plataforma"/>
 <tile id="317" type="Plataforma"/>
 <tile id="318" type="Plataforma"/>
 <tile id="319" type="Plataforma"/>
 <tile id="320" type="Plataforma"/>
 <tile id="321" type="Plataforma"/>
 <tile id="322" type="Plataforma"/>
 <tile id="323" type="Plataforma"/>
 <tile id="324" type="Plataforma"/>
 <tile id="325" type="Plataforma"/>
 <tile id="326" type="Plataforma"/>
 <tile id="327" type="Plataforma"/>
 <tile id="328" type="Plataforma"/>
 <tile id="329" type="Plataforma"/>
 <tile id="330" type="Plataforma"/>
 <tile id="331" type="Plataforma"/>
 <tile id="332" type="Plataforma"/>
 <tile id="333" type="Plataforma"/>
 <tile id="334" type="Plataforma"/>
 <tile id="335" type="Plataforma"/>
 <tile id="336" type="Plataforma"/>
 <tile id="337" type="Plataforma"/>
 <tile id="338" type="Plataforma"/>
 <tile id="339" type="Plataforma"/>
 <tile id="340" type="Plataforma"/>
 <tile id="341" type="Plataforma"/>
 <tile id="342" type="Plataforma"/>
 <tile id="343" type="Plataforma"/>
 <tile id="344" type="Plataforma"/>
 <tile id="345" type="Plataforma"/>
 <tile id="346" type="Plataforma"/>
 <tile id="347" type="Plataforma"/>
 <tile id="348" type="Plataforma"/>
 <tile id="349" type="Plataforma"/>
 <tile id="350" type="Plataforma"/>
 <tile id="351" type="Plataforma"/>
 <tile id="352" type="Plataforma"/>
 <tile id="353" type="Plataforma"/>
 <tile id="354" type="Plataforma"/>
 <tile id="355" type="Plataforma"/>
 <tile id="356" type="Plataforma">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="0" width="20" height="32"/>
  </objectgroup>
 </tile>
 <tile id="357" type="Plataforma"/>
 <tile id="358" type="Plataforma"/>
 <tile id="359" type="Plataforma"/>
 <tile id="360" type="Plataforma"/>
 <tile id="361" type="Plataforma"/>
 <tile id="362" type="Plataforma"/>
 <tile id="363" type="Plataforma"/>
 <tile id="364" type="Plataforma"/>
 <tile id="365" type="Plataforma"/>
 <tile id="366" type="Plataforma"/>
 <tile id="367" type="Plataforma"/>
 <tile id="368" type="Plataforma"/>
 <tile id="369" type="Plataforma"/>
 <tile id="370" type="Plataforma"/>
 <tile id="371" type="Plataforma"/>
 <tile id="372" type="Plataforma"/>
 <tile id="373" type="Plataforma"/>
 <tile id="374" type="Plataforma"/>
 <tile id="375" type="Plataforma"/>
 <tile id="376" type="Plataforma"/>
 <tile id="377" type="Plataforma"/>
 <tile id="378" type="Plataforma"/>
 <tile id="379" type="Plataforma"/>
 <tile id="380" type="Plataforma"/>
 <tile id="381" type="Plataforma"/>
 <tile id="382" type="Plataforma"/>
 <tile id="383" type="Plataforma"/>
 <tile id="384" type="Plataforma"/>
 <tile id="385" type="Plataforma"/>
 <tile id="386" type="Plataforma"/>
 <tile id="387" type="Plataforma"/>
 <tile id="388" type="Plataforma"/>
 <tile id="389" type="Plataforma"/>
 <tile id="390" type="Plataforma"/>
 <tile id="391" type="Plataforma"/>
 <tile id="392" type="Plataforma"/>
 <tile id="393" type="Plataforma"/>
 <tile id="394" type="Plataforma"/>
 <tile id="395" type="Plataforma"/>
 <tile id="396" type="Plataforma"/>
 <tile id="397" type="Plataforma"/>
 <tile id="398" type="Plataforma"/>
 <tile id="399" type="Plataforma"/>
 <tile id="400" type="Plataforma"/>
 <tile id="401" type="Plataforma"/>
 <tile id="402" type="Plataforma"/>
 <tile id="403" type="Plataforma"/>
 <tile id="404" type="Plataforma"/>
 <tile id="405" type="Plataforma"/>
 <tile id="406" type="Plataforma"/>
 <tile id="407" type="Plataforma"/>
 <tile id="408" type="Plataforma"/>
 <tile id="409" type="Plataforma"/>
 <tile id="410" type="Plataforma"/>
 <tile id="411" type="Plataforma"/>
 <tile id="412" type="Plataforma"/>
 <tile id="413" type="Plataforma"/>
 <tile id="414" type="Plataforma"/>
 <tile id="415" type="Plataforma"/>
 <tile id="416" type="Plataforma"/>
 <tile id="417" type="Plataforma"/>
 <tile id="418" type="Plataforma"/>
 <tile id="419" type="Plataforma"/>
 <tile id="420" type="Plataforma"/>
 <tile id="421" type="Plataforma"/>
 <tile id="422" type="Plataforma"/>
 <tile id="423" type="Plataforma"/>
 <tile id="424" type="Plataforma"/>
 <tile id="425" type="Plataforma"/>
 <tile id="426" type="Plataforma"/>
 <tile id="427" type="Plataforma"/>
 <tile id="428" type="Plataforma"/>
 <tile id="429" type="Plataforma"/>
 <tile id="430" type="Plataforma"/>
 <tile id="431" type="Plataforma"/>
 <tile id="432" type="Plataforma"/>
 <tile id="433" type="Plataforma"/>
 <tile id="434" type="Plataforma"/>
 <tile id="435" type="Plataforma"/>
 <tile id="436" type="Plataforma"/>
 <tile id="437" type="Plataforma"/>
 <tile id="438" type="Plataforma"/>
 <tile id="439" type="Plataforma"/>
 <tile id="440" type="Plataforma"/>
 <tile id="441" type="Plataforma"/>
 <tile id="442" type="Plataforma"/>
 <tile id="443" type="Plataforma"/>
 <tile id="444" type="Plataforma"/>
 <tile id="445" type="Plataforma"/>
 <tile id="446" type="Plataforma"/>
 <tile id="447" type="Plataforma"/>
 <tile id="448" type="Plataforma"/>
 <tile id="449" type="Plataforma"/>
 <tile id="450" type="Plataforma"/>
 <tile id="451" type="Plataforma"/>
 <tile id="452" type="Plataforma"/>
 <tile id="453" type="Plataforma"/>
 <tile id="454" type="Plataforma"/>
 <tile id="455" type="Plataforma"/>
 <tile id="456" type="Plataforma"/>
 <tile id="457" type="Plataforma"/>
 <tile id="458" type="Plataforma"/>
 <tile id="459" type="Plataforma"/>
 <tile id="460" type="Plataforma"/>
 <tile id="461" type="Plataforma"/>
 <tile id="462" type="Plataforma"/>
 <tile id="463" type="Plataforma"/>
 <tile id="464" type="Plataforma"/>
 <tile id="465" type="Plataforma"/>
 <tile id="466" type="Plataforma"/>
 <tile id="467" type="Plataforma"/>
 <tile id="468" type="Plataforma"/>
 <tile id="469" type="Plataforma"/>
 <tile id="470" type="Plataforma"/>
 <tile id="471" type="Plataforma"/>
 <tile id="472" type="Plataforma"/>
 <tile id="473" type="Plataforma"/>
 <tile id="474" type="Plataforma"/>
 <tile id="475" type="Plataforma"/>
 <tile id="476" type="Plataforma"/>
 <tile id="477" type="Plataforma"/>
 <tile id="478" type="Plataforma"/>
 <tile id="479" type="Plataforma"/>
 <tile id="480" type="Plataforma"/>
 <tile id="481" type="Plataforma"/>
 <tile id="482" type="Plataforma"/>
 <tile id="483" type="Plataforma"/>
 <tile id="484" type="Plataforma"/>
 <tile id="485" type="Plataforma"/>
 <tile id="486" type="Plataforma"/>
 <tile id="487" type="Plataforma"/>
 <tile id="488" type="Plataforma"/>
 <tile id="489" type="Plataforma"/>
 <tile id="490" type="Plataforma"/>
 <tile id="491" type="Plataforma"/>
 <tile id="492" type="Plataforma"/>
 <tile id="493" type="Plataforma"/>
 <tile id="494" type="Plataforma"/>
 <tile id="495" type="Plataforma"/>
 <tile id="496" type="Plataforma"/>
 <tile id="497" type="Plataforma"/>
 <tile id="498" type="Plataforma"/>
 <tile id="499" type="Plataforma"/>
 <tile id="500" type="Plataforma"/>
 <tile id="501" type="Plataforma"/>
 <tile id="502" type="Plataforma"/>
 <tile id="503" type="Plataforma"/>
 <tile id="504" type="Plataforma"/>
 <tile id="505" type="Plataforma"/>
 <tile id="506" type="Plataforma"/>
 <tile id="507" type="Plataforma"/>
 <tile id="508" type="Plataforma"/>
 <tile id="509" type="Plataforma"/>
 <tile id="510" type="Plataforma"/>
 <tile id="511" type="Plataforma"/>
 <tile id="512" type="Plataforma"/>
 <tile id="513" type="Plataforma"/>
 <tile id="514" type="Plataforma"/>
 <tile id="515" type="Plataforma"/>
 <tile id="516" type="Plataforma"/>
 <tile id="517" type="Plataforma"/>
 <tile id="518" type="Plataforma"/>
 <tile id="519" type="Plataforma"/>
 <tile id="520" type="Plataforma"/>
 <tile id="521" type="Plataforma"/>
 <tile id="522" type="Plataforma"/>
 <tile id="523" type="Plataforma"/>
 <tile id="524" type="Plataforma"/>
 <tile id="525" type="Plataforma"/>
 <tile id="526" type="Plataforma"/>
 <tile id="527" type="Plataforma"/>
 <tile id="528" type="Plataforma"/>
 <tile id="529" type="Plataforma"/>
 <tile id="530" type="Plataforma"/>
 <tile id="531" type="Plataforma"/>
 <tile id="532" type="Plataforma"/>
 <tile id="533" type="Plataforma"/>
 <tile id="534" type="Plataforma"/>
 <tile id="535" type="Plataforma"/>
 <tile id="536" type="Plataforma"/>
 <tile id="537" type="Plataforma"/>
 <tile id="538" type="Plataforma"/>
 <tile id="539" type="Plataforma"/>
 <tile id="540" type="Plataforma"/>
 <tile id="541" type="Plataforma"/>
 <tile id="542" type="Plataforma"/>
 <tile id="543" type="Plataforma"/>
 <tile id="544" type="Plataforma"/>
 <tile id="545" type="Plataforma"/>
 <tile id="546" type="Plataforma"/>
 <tile id="547" type="Plataforma"/>
 <tile id="548" type="Plataforma"/>
 <tile id="549" type="Plataforma"/>
 <tile id="550" type="Plataforma"/>
 <tile id="551" type="Plataforma"/>
 <tile id="552" type="Plataforma"/>
 <tile id="553" type="Plataforma"/>
 <tile id="554" type="Plataforma"/>
 <tile id="555" type="Plataforma"/>
 <tile id="556" type="Plataforma"/>
 <tile id="557" type="Plataforma"/>
 <tile id="558" type="Plataforma"/>
 <tile id="559" type="Plataforma"/>
 <tile id="560" type="Plataforma"/>
 <tile id="561" type="Plataforma"/>
 <tile id="562" type="Plataforma"/>
 <tile id="563" type="Plataforma"/>
 <tile id="564" type="Plataforma"/>
 <tile id="565" type="Plataforma"/>
 <tile id="566" type="Plataforma"/>
 <tile id="567" type="Plataforma"/>
 <tile id="568" type="Plataforma"/>
 <tile id="569" type="Plataforma"/>
 <tile id="570" type="Plataforma"/>
 <tile id="571" type="Plataforma"/>
 <tile id="572" type="Plataforma"/>
 <tile id="573" type="Plataforma"/>
 <tile id="574" type="Plataforma"/>
 <tile id="575" type="Plataforma">
  <objectgroup draworder="index" id="2">
   <object id="1" x="0" y="0" width="32" height="9"/>
   <object id="2" x="0" y="0" width="32" height="9"/>
  </objectgroup>
 </tile>
</tileset>
